<a href="https://colab.research.google.com/github/SH0123/DeepLearning/blob/master/TensorManipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import torch

2D array with numpy

In [0]:
#2D array with numpy
t = np.array([[1.,2.,3.], [4.,5.,6.], [7.,8.,9.], [10.,11.,12.]])
print(t)
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

2D array with pytorch

In [11]:
tensor = torch.FloatTensor([[1.,2.,3.], 
                       [4.,5.,6.], 
                       [7.,8.,9.], 
                       [10.,11.,12.]])
print(tensor)
print(tensor.dim())
print(tensor.size())
print(tensor[:, 1])
print(tensor[:, 1].size())
print(tensor[:, :-1])

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [17]:
#vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]] (1,) -> (1, 2)

print(m1 + m2)

tensor([[4., 5.]])


In [16]:
# 2 X 1 vector + 1 X 2 vector
m1 = torch.FloatTensor([[5], [7]]) #(2, 1) -> (2, 2)
m2 = torch.FloatTensor([[10, 11]]) #(1, 2) -> (2, 2)

print(m1 + m2)

tensor([[15., 16.],
        [17., 18.]])


In [20]:
# matmul != mul or *
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[2], [2]])

print('matmul : ', m1.matmul(m2))
print('* : ', m1 * m2)
print('mul : ', m1.mul(m2))

matmul :  tensor([[ 6.],
        [14.]])
* :  tensor([[2., 4.],
        [6., 8.]])
mul :  tensor([[2., 4.],
        [6., 8.]])


Mean, argmax, sum 등에서의 dim에 대한 이해

In [28]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.shape)
print(t.mean())
print(t.mean(dim=0)) # 0번째 차원을 압축시키겠다!
print(t.mean(dim=1)) # 1번째 차원을 압축시키겠다!

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
