In [0]:
import numpy as np
import torch

2D array with numpy

In [0]:
#2D array with numpy
t = np.array([[1.,2.,3.], [4.,5.,6.], [7.,8.,9.], [10.,11.,12.]])
print(t)
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

2D array with pytorch

In [0]:
tensor = torch.FloatTensor([[1.,2.,3.], 
                       [4.,5.,6.], 
                       [7.,8.,9.], 
                       [10.,11.,12.]])
print(tensor)
print(tensor.dim())
print(tensor.size())
print(tensor[:, 1])
print(tensor[:, 1].size())
print(tensor[:, :-1])

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [0]:
#vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]] (1,) -> (1, 2)

print(m1 + m2)

tensor([[4., 5.]])


In [0]:
# 2 X 1 vector + 1 X 2 vector
m1 = torch.FloatTensor([[5], [7]]) #(2, 1) -> (2, 2)
m2 = torch.FloatTensor([[10, 11]]) #(1, 2) -> (2, 2)

print(m1 + m2)

tensor([[15., 16.],
        [17., 18.]])


In [0]:
# matmul != mul or *
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[2], [2]])

print('matmul : ', m1.matmul(m2))
print('* : ', m1 * m2)
print('mul : ', m1.mul(m2))

matmul :  tensor([[ 6.],
        [14.]])
* :  tensor([[2., 4.],
        [6., 8.]])
mul :  tensor([[2., 4.],
        [6., 8.]])


Mean, argmax, sum 등에서의 dim에 대한 이해

In [0]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.shape)
print(t.mean())
print(t.mean(dim=0)) # 0번째 차원을 압축시키겠다!
print(t.mean(dim=1)) # 1번째 차원을 압축시키겠다!

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])


View

In [10]:
t = np.array([[[1, 2, 3], [4, 5, 6]],
              [[7, 8, 9], [10, 11, 12]]])
tensor= torch.FloatTensor(t)
print(t.shape)
print(tensor.view([-1, 3]))
print(tensor.view((-1, 3)).shape)

(2, 2, 3)
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
torch.Size([4, 3])


Concatenate

In [9]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

print(torch.cat((x, y), dim=0))
print(torch.cat((x, y), dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


Ones and Zeros

In [15]:
x = torch.randn(3, 4)
print(x)

#gpu, cpu 구분할 때 같은 device에서 생성할 수 있도록 사용해주는 것
ones = torch.ones_like(x)
zeros = torch.zeros_like(x)
print("ones : ", ones)
print("zeros : ", zeros)

tensor([[ 0.7293,  2.1373, -0.0144, -0.3753],
        [-1.2144,  1.6372, -1.7254,  1.5934],
        [-1.0271, -1.2741, -0.3146,  1.4261]])
ones :  tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
zeros :  tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In-place operation

In [16]:
x = torch.FloatTensor([[1, 2], [3, 4]])

print(x.mul(2))
print(x)
print(x.mul_(2))#inplace할 때 _사용해야 함
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
